/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 05edf603d7410171f856b5063898151d)
interface __BaseEnv_Env {
	ACCOUNT_ISSUER: "";
	ACCOUNT_AUDIENCE: "";
	ACCOUNT_JWKS_URL: "";
	ONBOARDING_RETURN_URL: "";
	ONBOARDING_REFRESH_URL: "";
	CHECKOUT_SUCCESS_URL: "";
	CHECKOUT_CANCEL_URL: "";
	PAYMENT_CONNECTIONS: DurableObjectNamespace<import("./src/cloudflare/worker").PaymentConnection>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/worker");
		durableNamespaces: "PaymentConnection";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNT_ISSUER" | "ACCOUNT_AUDIENCE" | "ACCOUNT_JWKS_URL" | "ONBOARDING_RETURN_URL" | "ONBOARDING_REFRESH_URL" | "CHECKOUT_SUCCESS_URL" | "CHECKOUT_CANCEL_URL">> {}
}
